### ISSUE TITLE
Unexpected error while changing config Active tab

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#105]
I was looking at options in the Active tab and changed some options just to see what the GUI offered. (Forgot that the view tries to apply the change after a 5 second delay.) 

the following Unexpected Error occured:
```
304377: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\linked_view.py", line 258, in _perform_config_refresh
    self.build_tree()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\linked_view.py", line 601, in build_tree
    self.change_object(active_object)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\linked_view.py", line 655, in change_object
    self._render_page(page_context)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\linked_view.py", line 678, in _render_page
    page.render_page(self.page_view, page_context)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\pages\page_base.py", line 131, in render_page
    object_view = view_builder(self.grstate, context)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\views\view_builder.py", line 90, in view_builder
    return view(grstate, grcontext)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\views\view_person.py", line 41, in __init__
    GrampsObjectView.__init__(self, grstate, grcontext)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\views\view_base.py", line 67, in __init__
    self.render_view()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\views\view_base.py", line 73, in render_view
    self.build_view()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\views\view_person.py", line 59, in build_view
    self.grstate, groptions, person.obj
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\frames\frame_person.py", line 145, in __init__
    self.load_fields(event_cache, "extra-field", extra=True)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\frames\frame_person.py", line 258, in load_fields
    option[1], extra=extra, show_all=show_all
UnboundLocalError: local variable 'show_all' referenced before assignment
```
![image](https://user-images.githubusercontent.com/69127217/145555643-d1c26199-abc7-482d-ba5e-16a755c18392.png)

**Comment by emyoulation** [comment]
Note that the LinkedView became disabled after this error.  When switching to the view, it remained blank (no feedback of error state) and even after using the reset to default, switching view, switching focus person and re-entering the LinkedView; it remained blank.

The View did not populate again until exiting Gramps and restarting it.

**Comment by cdhorn** [comment]
Closing this as well now. In the refactor I decided it was not worth keeping the show all option so removed it altogether.
