### ISSUE TITLE
AttributeError: No such config setting name: 'active.note.include-child-objects'

### ISSUE THREAD

**Issue by wroldwiedbwe** [cdhorn/LinkedView#131]
Great addon 👍 

Came across the following issue.

User Information: 
===================
* Selected the "Browse" category (needs a better name? and can it appear under the Dashboard category?)
* Select "configure the view"
* on the "Default" template select the "Edit Template" button
* on the "Template Editor" select the "Active" tab
* on the  "Active" tab select the "Note" entry in the left hand column

Which gives me the "Error Report Assistant" with the following this report.

Error Details: 
===================

395391: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\config_objects.py", line 102, in handle_page_switch
    page = render_page()
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\config_panel.py", line 186, in <lambda>
    render_page = lambda: build_note_grid(configdialog, grstate, space)
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\config_objects.py", line 492, in build_note_grid
    "{}.note.include-child-objects".format(space),
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\configure_dialog.py", line 283, in add_checkbox
    checkbox.set_active(config.get(constant))
  File "Z:\PortableApps\GrampsPortable\App\Gramps\gramps\gen\utils\configmanager.py", line 382, in get
    (section, setting))
AttributeError: No such config setting name: 'active.note.include-child-objects'

416561: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\config_objects.py", line 102, in handle_page_switch
    page = render_page()
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\config_panel.py", line 186, in <lambda>
    render_page = lambda: build_note_grid(configdialog, grstate, space)
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\config_objects.py", line 492, in build_note_grid
    "{}.note.include-child-objects".format(space),
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\configure_dialog.py", line 283, in add_checkbox
    checkbox.set_active(config.get(constant))
  File "Z:\PortableApps\GrampsPortable\App\Gramps\gramps\gen\utils\configmanager.py", line 382, in get
    (section, setting))
AttributeError: No such config setting name: 'active.note.include-child-objects'

443212: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\config_objects.py", line 102, in handle_page_switch
    page = render_page()
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\config_panel.py", line 186, in <lambda>
    render_page = lambda: build_note_grid(configdialog, grstate, space)
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\config_objects.py", line 492, in build_note_grid
    "{}.note.include-child-objects".format(space),
  File "Z:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\LinkedView-master\view\config\configure_dialog.py", line 283, in add_checkbox
    checkbox.set_active(config.get(constant))
  File "Z:\PortableApps\GrampsPortable\App\Gramps\gramps\gen\utils\configmanager.py", line 382, in get
    (section, setting))
AttributeError: No such config setting name: 'active.note.include-child-objects'

System Information: 
===================

Gramps version: AIO32-5.1.5-1 
Python version: 3.6.4 (default, Jan 23 2018, 13:40:26)  [GCC 7.2.0 32 bit] 
BSDDB version: 6.1.0 (6, 0, 30) 
sqlite version: 3.21.0 (2.6.0) 
LANG: en_GB.UTF-8
OS: Windows

GTK version    : 3.18.9
gobject version: 3.26.1
cairo version  : (1, 16, 1)

**Comment by cdhorn** [comment]
Thanks for reporting this, sorry for delayed response have been on a bit of a hiatus recently. Should be fixed, that was meant to only be a group level option.

> Selected the "Browse" category (needs a better name? and can it appear under the Dashboard category?)

It's not really a Dashboard so to me that seems out of place.  It was for a time a view under the Relationships category as it had its roots in Nick's Combined View but because you can browse almost everything, at least in the present incarnation, it seemed best to make a new category for it.

**Comment by wroldwiedbwe** [comment]
Thanks for the fix.

> It's not really a Dashboard,  so to me that seems out of place. 

I agree,  but now that you have moved the cards into each category, I'm thinking that for the Dashboard, you just show all of the cardview icons on the toolbar ( including the help/livesaver icon) so you don't have to visit each of the individual categories, I reckon this could be configurable ( all turned on or off or individually?),  it would in my mind make the dashboard  more usefull?

**Comment by cdhorn** [comment]
I need a set of icons for the card view still, at the moment I just recycled the one I was using when it was called the link view for all of them.  So there is nothing to differentiate them.

I might have an idea for something to do with the dashboard at some point but for now am trying hard to focus on refining what I have to date to try to get something out the door and into more hands.

**Comment by wroldwiedbwe** [comment]
> but for now am trying hard to focus on refining what I have to date to try to get something out the door and into more hands.

@cdhorn Is adding something to the Dashboard https://github.com/cdhorn/CardView/issues/196  essential for addon to be rolled out as is? 

I feel the majority of issues/error users will run into have been taken care of already and can be enhanced later on?

I have ideas for the dashboard as I suggested above  but like you mention get a version of it into more hands.


(fyi @emyoulation  suggested the following https://github.com/cdhorn/CardView/issues/158 )
