### ISSUE TITLE
Switching between views with No Tree Loaded is problematic

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#133]
When stating Gramps with no database open & remember last view restoring to the Linked/Browse view, the GUI is unresponsive and generates errors. The other view's still allow the GUI to be manipulated in preparation to accept data.

I was unable to disable/re-enable the Browse/Linked view's sidebar or bottombar when no Tree is loaded. And navigating to another view popped an error.

Note that the Status bar reports "No active object" when the more important issue is that no tree is loaded. 

Gramps was launched via the Console option, this log was delivered to the CLI console (the portion beginning with "Error" popped up in an Unexpected error dialog.) :
```
2022-05-06 20:24:22.329: WARNING: dummydb.py: line 685: database is closed
2022-05-06 20:26:12.516: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\plugins\sidebar\dropdownsidebar.py", line 119, in __category_clicked
    self.viewmanager.goto_page(cat_num, None)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\viewmanager.py", line 786, in goto_page
    self.__create_page(page_def[0], page_def[1])
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\viewmanager.py", line 840, in __create_page
    self.active_page.post_create()
AttributeError: 'NoneType' object has no attribute 'post_create'
```

**Comment by cdhorn** [comment]
This is a bug in Gramps core, not this view in particular.  I am able to reproduce this using only the list views.

**Comment by cdhorn** [comment]
Closing this as a result, should open a bug in Mantis.
