### ISSUE TITLE
Unknown causes of GTK messages in log

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#134]
I did not notice the `(gramps.exe:12372): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed` messages appearing in the Console.  I was testing (and loving) the new responsiveness in the Context menu appearance. However, I had noticed there were DIFFERENT context menus depending upon which element within a panel was clicked.  So I was clicking different elements. (It was a bit odd that a right-click outside the context menu simply dismisses the Context menu, it doesn't initiate a new context menu for the indicated element.) Then I belatedly noticed the pink Gtk-CRITCAL messages in the Console.  

Future clicks did not add messages.  So I tried closing the Tree and reloading. Then right-clicking some more.  And finally did some left-clicks to change the View focus and then tried more right-click context menus. No joy.

So here's the Console log if that helps at all.

```
2022-05-06 20:24:22.329: WARNING: dummydb.py: line 685: database is closed
2022-05-06 20:26:12.516: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\plugins\sidebar\dropdownsidebar.py", line 119, in __category_clicked
    self.viewmanager.goto_page(cat_num, None)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\viewmanager.py", line 786, in goto_page
    self.__create_page(page_def[0], page_def[1])
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\viewmanager.py", line 840, in __create_page
    self.active_page.post_create()
AttributeError: 'NoneType' object has no attribute 'post_create'

Warning: ExtendedHistory: Exception occurred in callback function.
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\utils\callback.py", line 409, in emit
    fn(*args)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView-master\extended_navigation.py", line 263, in goto_active
    self.goto_handle(current_handle)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView-master\linked_view.py", line 684, in goto_handle
    self.change_object(handle)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView-master\linked_view.py", line 734, in change_object
    page_context.load_page_location(self.grstate, obj_tuple)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView-master\view\common\common_classes.py", line 471, in load_page_location
    primary_obj = grstate.fetch(primary_obj_type, primary_obj_handle)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView-master\view\common\common_classes.py", line 586, in fetch
    return self.methods[obj_type](obj_handle)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\db\generic.py", line 1282, in get_person_from_handle
    return self._get_from_handle(PERSON_KEY, Person, handle)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\db\generic.py", line 1266, in _get_from_handle
    data = self._get_raw_data(obj_key, handle)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\plugins\db\dbapi\dbapi.py", line 869, in _get_raw_data
    self.dbapi.execute(sql, [handle])
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\plugins\db\dbapi\sqlite.py", line 133, in execute
    self.__cursor.execute(*args, **kwargs)
sqlite3.ProgrammingError: Cannot operate on a closed database.
render_page: I0000044 6.587559700012207

(gramps.exe:12372): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gramps.exe:12372): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gramps.exe:12372): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gramps.exe:12372): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gramps.exe:12372): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gramps.exe:12372): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
render_page: I0000044 2.5592105388641357
render_page: I0001117 0.6230001449584961
render_page: I0001117 1.86799955368042

```

**Comment by cdhorn** [comment]
The earlier post_create error is a bug in Gramps core.

Regarding:

(gramps.exe:12372): Gtk-CRITICAL **: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

These are annoying and are a result of how the pop up menu works. In and of themselves they have not caused a problem for me. I've been meaning to experiment to see if the context menus elsewhere in Gramps cause the same asserts sometimes. I suspect so. I need to ask someone more knowledgeable like Nick or Paul about them.
