### ISSUE TITLE
Changing statistics configuration to Tabbed mode froze Gramps

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#209]
To start, I probably have an old format of the Configuration templates. (This is sure to happen in the future as CardView configuration evolves. _Perhaps the configuration files could store the version number of CardView where it was saved? Then each card view could have a backwards compatibility version limit where you decide if a version is too old to be safe to load?_)

But I was in the Statistics dashboard for the example.gramps (active record home person Garner von Zielinski)
went into configure, and selected the minimal template to Edit 
changed the layout of Statistics to Tabbed mode, applied, saved, closed Configure
Layout did not refresh, so clicked the link to the Home Person in the in the Family Tree Summary panel, appeared to start refresh

An unexpected Error occurred but I could not expand the Details.  Gramps was frozen
from the CLI launch window:

```
render_page: statistics 0.269040584564209
stats collected: 3.563861846923828
render_page: statistics 0.3770408630371094
update change hist emitting
2022-09-05 21:13:28.274: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>i
2022-09-05 21:13:28.276: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>b
2022-09-05 21:13:28.277: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>u
2022-09-05 21:13:28.278: WARNING: uimanager.py: line 386: **Duplicate Accelerator <primary>z
2022-09-05 21:13:28.279: WARNING: uimanager.py: line 386: **Duplicate Accelerator <primary><shift>z
render_page: statistics 0.41103386878967285
update change hist emitting
2022-09-05 21:14:47.575: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>i
2022-09-05 21:14:47.576: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>b
2022-09-05 21:14:47.577: WARNING: uimanager.py: line 386: **Duplicate Accelerator <PRIMARY>u
2022-09-05 21:14:47.578: WARNING: uimanager.py: line 386: **Duplicate Accelerator <primary>z
2022-09-05 21:14:47.579: WARNING: uimanager.py: line 386: **Duplicate Accelerator <primary><shift>z
render_page: statistics 0.34998035430908203
update change hist emitting
render_page: statistics 0.365001916885376
update change hist emitting
render_page: statistics 0.44598937034606934
Warning: SQLite: Exception occurred in callback function.
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\utils\callback.py", line 409, in emit
    fn(*args)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\CardView-master\src\view\services\service_statistics.py", line 148, in <lambda>
    update_function = lambda x: self.update_change_history(x, object_type)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\CardView-master\src\view\services\service_statistics.py", line 339, in update_change_history
    self.clean_change_history(object_type, object_handle)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\CardView-master\src\view\services\service_statistics.py", line 407, in clean_change_history
    for object_data in self.change_history[index]:
KeyError: 'Global'
render_page: statistics 0.3099970817565918
render_page: statistics 0.320965051651001
render_page: dashboard 0.06603813171386719
stats collected: 3.665203332901001
2022-09-05 21:31:13.976: WARNING: _gramplet.py: line 342: Gramplet gave an error: PropertyEditor
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\plug\_gramplet.py", line 326, in _updater
    retval = next(self._generator)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\PropertyEditor\PropertyEditor.py", line 82, in main
    self.objname=self.cls.__name__.lower()
AttributeError: 'PropertyEditor' object has no attribute 'cls'
Continuing after gramplet error...
render_page: N000017 0.42694902420043945
render_page: _header1 0.597001314163208
render_page: N000017 0.40200042724609375
render_page: statistics 0.4379761219024658
render_page: dashboard 0.3020341396331787
render_page: statistics 0.39551448822021484
update change hist emitting
render_page: dashboard 0.17000198364257812
render_page: statistics 0.40599870681762695
render_page: dashboard 0.21905064582824707
render_page: statistics 0.4950406551361084
render_page: dashboard 0.810011625289917
render_page: statistics 0.4760007858276367
render_page: dashboard 0.22999882698059082
render_page: statistics 0.3865671157836914
update change hist emitting
render_page: dashboard 0.1750047206878662
render_page: N000017 0.48804593086242676
render_page: statistics 0.4050116539001465
update change hist emitting
render_page: dashboard 0.011008739471435547
render_page: N000017 0.4889943599700928
stats collected: 9.693403244018555
render_page: statistics 0.41300082206726074
render_page: dashboard 0.18800067901611328
render_page: statistics 0.48599910736083984
render_page: dashboard 0.17299365997314453
render_page: statistics 0.3959989547729492
update change hist emitting
render_page: dashboard 0.17299437522888184
render_page: statistics 0.4030141830444336
update change hist emitting
render_page: dashboard 0.17504429817199707
render_page: statistics 0.483001708984375
render_page: I0000044 2.803248643875122
2022-09-06 09:36:43.569: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\views\pageview.py", line 186, in set_page_slider
    vp_ch = side_ch[0].get_children()  # Gtk Viewport child
IndexError: list index out of range

```

**Comment by cdhorn** [comment]
Yeah nothing here related to templates, likely some race condition with the statistics service.
