### ISSUE TITLE
TypeError: unhashable type: 'Person'

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#81]
Downloaded an update today and got an error when switching views. 

BTW, I like the Category navigator in the Configuration.  I wonder... since a lot of these categorizes have the same options, might there be an opportunity for a GUI to select more than one category (or all categories) and simultaneously harmonize the options of the same name?  

```
695077: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gui\viewmanager.py", line 969, in __open_activate
    self._post_load_newdb(filename, 'x-directory/normal', title)
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gui\viewmanager.py", line 1006, in _post_load_newdb
    self._post_load_newdb_gui(filename, filetype, title)
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gui\viewmanager.py", line 1046, in _post_load_newdb_gui
    self.__change_page(self.notebook.get_current_page())
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gui\viewmanager.py", line 885, in __change_page
    self.active_page.set_active()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\profileview-master\profileview.py", line 805, in set_active
    ExtendedNavigationView.set_active(self)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\profileview-master\enavigationview.py", line 200, in set_active
    PageView.set_active(self)
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gui\views\pageview.py", line 338, in set_active
    self.build_tree()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\profileview-master\profileview.py", line 279, in build_tree
    self.redraw()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\profileview-master\profileview.py", line 612, in redraw
    self.change_object(None)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\profileview-master\profileview.py", line 694, in change_object
    obj_tuple = self._get_last()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\profileview-master\profileview.py", line 633, in _get_last
    initial_person = self.fetch_object("Person", initial_person_handle)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\profileview-master\profileview.py", line 156, in fetch_object
    if handle in self.cache:
TypeError: unhashable type: 'Person'
```

Fresh download 4Sep2021

**Comment by cdhorn** [comment]
Ah, thanks, mishandled that for sure! Should be fixed in ea81020a5f9e441e0258715da8e49e313242da58

Regarding category options that thought has occurred to me too but a good way of handling it doesn't immediately come to mind.

I like the thought of letting the user customize as much as possible, but doing so obviously has drawbacks as well. So it is a matter of finding the right or a reasonable balance.

I could simplify it more and say the same config applies to all people in the group layouts and collapse Parent/Sibling/Spouse/Child/Participant/Association into just Person.

Or factor out say tags, event format and image mode and make them common to all the groups or even globally instead of per category.

Perhaps I should do one or the other or both, I'm not sure. The original design allowed for a much finer level of control and as you know I already scaled it back as that was clearly too much. Maybe the current setup is still too much and needs to be pulled in even more.
