### ISSUE TITLE
Warnings from command line on start

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/LinkedView#97]
LinkedView  version 0.60

Set Gramps Preferences "Remember last view displayed" enabled,  & "Automatically load last Family Tree" disabled. Make LinkedView as view selected when quitting 

Start Gramps from the command line.  
The following messages appear in the CLI before the Famile Tree select dialog appears

2021-12-06 20:12:38.637: WARNING: dummydb.py: line 787: database is closed
2021-12-06 20:12:38.638: WARNING: dummydb.py: line 788: handle  does not exist in the dummy database

open a Tree ( I opened an example.gramps import.)

2021-12-06 20:21:42.587: WARNING: dummydb.py: line 787: database is closed
2021-12-06 20:21:42.587: WARNING: dummydb.py: line 788: handle  does not exist in the dummy database
2021-12-06 20:21:42.673: WARNING: dummydb.py: line 834: database is closed
2021-12-06 20:21:42.673: WARNING: dummydb.py: line 835: handle GNUJQCL9MD64AM56OH does not exist in the dummy database
2021-12-06 20:21:42.759: WARNING: dummydb.py: line 834: database is closed
2021-12-06 20:21:42.760: WARNING: dummydb.py: line 835: handle 5UEKQC8N8NEPSWU1QQ does not exist in the dummy database
2021-12-06 20:21:42.830: WARNING: dummydb.py: line 533: database is closed
2021-12-06 20:21:42.830: WARNING: dummydb.py: line 534: handle d5839c123c034ef82ab does not exist in the dummy database
render_page: I0000044 2.4640016555786133

The "Database is closed" is common when Gramplets and views try to poll the loaded tree.  (Serge has a pull to move those messages from the CLI and status Bar warning handler  **LOG.warning** to **LOG.debug**   see  [Bug 12492](https://gramps-project.org/bugs/view.php?id=12492) and [PR 1311](https://github.com/gramps-project/gramps/pull/1311)  )  But I haven't seen the **Handle does not exist** message.

**Comment by cdhorn** [comment]
I have seen those occasionally. The dummy database has nothing in it so I've been ignoring them. I am unsure of reason, I suspect something to do with startup and the interaction with the RestoreHist plugin and maybe the new navigation/history classes trying to sync up with things.

**Comment by emyoulation** [comment]
Plugin name: Linked [Gramps View]
Id: linked_view
Version: 0.62
Filename: linked_view.py
Location: C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView

Loaded 


Console messages (loading Example.grams to the Dashboard, then switch to the LinkedView. Then attempt to reset Configuration to Defaults:

render_page: I0000044 1.8312032222747803
render_page: O000008 0.3581888675689697

(gramps.exe:11016): GdkPixbuf-CRITICAL **: gdk_pixbuf_scale_simple: assertion 'dest_height > 0' failed
render_page: I0000044 2.127127170562744
render_page: I0001106 0.9481935501098633
render_page: I0001106 0.6482164859771729
2021-12-08 11:34:12.335: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\LinkedView\view\common\common_utils.py", line 408, in reset_option_space
    default_value = self.config.get_default(option)
  File "C:\Program Files\GrampsAIO64-5.1.4\gramps\gen\utils\configmanager.py", line 429, in get_default
    (section, setting))
AttributeError: No such config setting name: 'options.colors.roles.border-other'

**Comment by cdhorn** [comment]
Glad I'm reviewing these. I need to test all the configuration reset to default stuff. I did not after the template refactor so much of it is likely broken.
